# Generated by Django 3.0.7 on 2021-06-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challan',
            old_name='challan1',
            new_name='ch1',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan2',
            new_name='ch2',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan3',
            new_name='ch3',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan4',
            new_name='ch4',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan5',
            new_name='ch5',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan6',
            new_name='ch6',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan7',
            new_name='ch7',
        ),
        migrations.RenameField(
            model_name='challan',
            old_name='challan8',
            new_name='ch8',
        ),
    ]
