# Generated by Django 3.0.7 on 2021-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_auto_20210624_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='ch1',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch2',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch3',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch4',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch5',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch6',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch7',
            field=models.CharField(default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='challan',
            name='ch8',
            field=models.CharField(default='00', max_length=20),
        ),
    ]
