# Generated by Django 3.0.7 on 2021-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetail',
            fields=[
                ('student_no', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('student_id', models.CharField(max_length=30)),
                ('student_mobile', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_pass', models.CharField(max_length=20)),
                ('student_dept', models.CharField(max_length=20)),
            ],
        ),
    ]
