# Generated by Django 3.0.7 on 2021-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectDetails',
            fields=[
                ('subject_no', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.CharField(max_length=2)),
                ('sub_id', models.CharField(max_length=250)),
                ('sub_detail', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_year',
            field=models.IntegerField(default=1998),
        ),
    ]
