# Generated by Django 3.0.7 on 2021-06-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2_manage', '0002_auto_20210606_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='student_dept',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student_pass',
            field=models.CharField(max_length=30),
        ),
    ]
