# Generated by Django 3.0.7 on 2021-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin2_manage', '0003_auto_20210606_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='student_gendere',
            field=models.CharField(default='MALE', max_length=10),
        ),
    ]
