# Generated by Django 3.0.7 on 2021-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybooks',
            name='book_ava',
            field=models.IntegerField(),
        ),
    ]
