# Generated by Django 3.0.7 on 2021-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymangement', '0003_auto_20210614_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybooks',
            name='book_author',
            field=models.CharField(max_length=255),
        ),
    ]
