# Generated by Django 3.0.7 on 2021-06-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymangement', '0005_bookstostudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstostudents',
            name='books_id',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='librarymangement.librarybooks'),
            preserve_default=False,
        ),
    ]
