# Generated by Django 3.0.7 on 2021-06-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymangement', '0006_bookstostudents_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstostudents',
            name='date_issue',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
