# Generated by Django 3.0.7 on 2021-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginadmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_mail', models.EmailField(max_length=254)),
                ('admin_pword', models.CharField(max_length=100)),
            ],
        ),
    ]
