# Generated by Django 3.0.7 on 2021-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginadmin',
            name='admin_panel',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Library'), (2, 'Exam'), (3, 'Placement')], default=0),
        ),
    ]
